### ISSUE TITLE
Why description capped at 140 characters?

### ISSUE THREAD

**Issue by pauldijou** [bower/json#22]
I'm using the JS API of Bower and several releases packages are throwing exceptions just because their description is more than [140 characters](https://github.com/bower/json/blob/cbadab875639e7c65f8c51b34311bcae142a8066/lib/json.js#L107-L109). It's quite problematic... Since Bower cannot prevent a package to be published with an invalid JSON (it's just a push on Github after all), it shouldn't have such strict validation rules IMO.

Obviously, there might be the same problem with the name validation with doesn't allow any uppercase and capped at 50 characters.

Since this is not Twitter and to be compatible with all currently published packages, I would rather remove those verifications. What do you think?

**Comment by cvrebert** [comment]
This would be a bug in the spec (https://github.com/bower/bower.json-spec/) rather than the parser/validator per se, IMHO.

**Comment by jmfarina** [comment]
Hello,
I'd like to second this issue. While I understand and concur with cvrebert's argument, I think that in practical terms this validation doesn't make much sense. With this validation in place, if the description of a package exceeds 140 characters there's no easy way to circumvent the problem for an end user (none I could find, at least - I had to find and edit the validation in json.js). Meanwhile, if the limit didn't apply, I think that there shouldn't be any side-effects, right?
I think that a more correct approach would be to have this validation raise a warning rather than an error. If you look at the specs, it says that description is recommended, not required. So, while technically I would be inclined to consider it an error, like I said, it's not practical.
Furthermore, this validation is a new introduction that clearly breaks compatibility with pre-existent libraries that didn't match this criteria, as pauldijou pointed out.
For all these reasons, I'd like to propose that this validation is demoted to a warning. And if this should REALLY be an error check, maybe introduce it in a few versions from now, provided there has been warning and time for devs to adjust their libraries.

**Comment by sheerun** [comment]
I made it a warning instead of an error.
