### ISSUE TITLE
Existing packages' names (i.e. d3) no longer valid due to stricter validation rules in 0.5.0

### ISSUE THREAD

**Issue by brian-gates** [bower/json#24]
D3 can no longer be installed as of bower-json 0.5.0:

> The name has to end with a lower case character from a to z

Other packages are invalidated by this rule as well:

> The name contains upper case letters

https://github.com/bower/json/blob/3cc1cd61c86d65c11fae42c05e2a4ce61310cbce/lib/json.js#L86-L114

This seems pretty huge.  Installs that worked last month no longer do, with no change on my end.

See also https://github.com/bower/bower/issues/1829

**Comment by seanhoughton** [comment]
This change just completely broke my build setup because I use both angular-md5 and d3. Both of these package names seem completely valid and don't violate the principal of not encoding version numbers in the package name. Would you suggest they rename the projects to angular-mdfive and dthree?

Any validation with false positives should be removed, especially when it can't be turned off except by manually deleting code or pinning to an old revision.

**Comment by sheerun** [comment]
Yeah. I think we need to either rollback or make this change backward-compatible. Will do it soon.

**Comment by sheerun** [comment]
I rollbacked any strict validations except for types of `name` and `main`.

Now you can use `bowerJson.getIssues(json)` to get extra warnings.

**Comment by brian-gates** [comment]
Yay! :+1:
